"""Tests for bot API client — HMAC hash generation and request building."""

from __future__ import annotations

import hashlib
import hmac
import os
import time
from unittest.mock import AsyncMock, patch

import pytest

from bot.services.api_client import APIClient


def _compute_expected_hash(
    telegram_id: int,
    username: str | None,
    first_name: str | None,
    last_name: str | None,
    auth_date: int,
    bot_token: str,
) -> str:
    """Reproduce the HMAC hash the bot client should generate."""
    fields: dict[str, str] = {"id": str(telegram_id), "auth_date": str(auth_date)}
    if first_name:
        fields["first_name"] = first_name
    if last_name:
        fields["last_name"] = last_name
    if username:
        fields["username"] = username
    data_check = "\n".join(f"{k}={fields[k]}" for k in sorted(fields))
    secret_key = hashlib.sha256(bot_token.encode()).digest()
    return hmac.new(secret_key, data_check.encode(), hashlib.sha256).hexdigest()


@pytest.mark.asyncio
async def test_auth_telegram_sends_hash():
    """auth_telegram includes hash and auth_date in the request body."""
    bot_token = "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"

    api = APIClient()

    fake_response = {"access_token": "jwt-token-here", "user": {"id": "u1"}}

    with patch.dict(os.environ, {"TELEGRAM_BOT_TOKEN": bot_token}):
        with patch.object(api, "_request", new_callable=AsyncMock, return_value=fake_response) as mock_req:
            result = await api.auth_telegram(
                telegram_id=12345,
                username="testuser",
                first_name="John",
                last_name="Doe",
            )

    assert result == fake_response
    assert api.token == "jwt-token-here"

    # Verify _request was called with correct args
    mock_req.assert_called_once()
    call_args = mock_req.call_args
    assert call_args[0][0] == "POST"
    assert call_args[0][1] == "/auth/telegram"
    body = call_args[1]["json"]
    assert body["telegram_id"] == 12345
    assert body["username"] == "testuser"
    assert body["first_name"] == "John"
    assert body["last_name"] == "Doe"
    assert isinstance(body["auth_date"], int)
    assert isinstance(body["hash"], str)
    assert len(body["hash"]) == 64  # SHA-256 hex


@pytest.mark.asyncio
async def test_auth_telegram_hash_is_valid():
    """The HMAC hash generated by auth_telegram matches expected Telegram Login Widget spec."""
    bot_token = "999888:XYZ-test-token"
    api = APIClient()

    captured_body: dict = {}

    async def capture_request(method: str, path: str, json: dict | None = None, **kw):
        captured_body.update(json or {})
        return {"access_token": "tok", "user": {"id": "u"}}

    with patch.dict(os.environ, {"TELEGRAM_BOT_TOKEN": bot_token}):
        with patch.object(api, "_request", side_effect=capture_request):
            await api.auth_telegram(
                telegram_id=42,
                username="alice",
                first_name="Alice",
                last_name=None,
            )

    expected = _compute_expected_hash(
        telegram_id=42,
        username="alice",
        first_name="Alice",
        last_name=None,
        auth_date=captured_body["auth_date"],
        bot_token=bot_token,
    )
    assert captured_body["hash"] == expected


def test_api_client_headers_with_token():
    """APIClient sets Authorization header when token is provided."""
    api = APIClient(token="my-jwt")
    assert api._headers == {"Authorization": "Bearer my-jwt"}


def test_api_client_headers_without_token():
    """APIClient returns empty headers when no token."""
    api = APIClient()
    assert api._headers == {}
